copy fortune button
StephenTan12/Horoscope-Team-5 pull request #52
Opened 2024-06-05 21:34 UTC by akann0

- created a copy fortune button which copies a given fortune into the clipboard
- meant to prototype a possible share to social media (x, instagram, etc) button

2024-06-06 08:22 UTC, Miyuki-L requested changes
Just a few small things but also pull from main to make sure all the new changes are present

2024-06-07 22:31 UTC, StephenTan12 commented on source/horoscope/js/history.js
> +        throw Error('This is an error');
was this line intended to be here or was it for testing purposes?

2024-06-08 05:44 UTC, VijayP30 commented on source/horoscope/css/pastEntryCard.css
> +button.copy {
Fixed. Now the card doesnt change size and there isnt shifting

2024-06-08 05:44 UTC, VijayP30 approved these changes

2024-06-08 05:45 UTC, merged